name: "PR Test build Docker"
on: 
  workflow_dispatch:
  pull_request:

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Check node version
        run: node -v

      - name: Build docker images
        run: docker build -t jarnesjo.com-dev .
        